// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RIGProjeck.Class;

#nullable disable

namespace RIGProjeck.Migrations
{
    [DbContext(typeof(NepremicninaDB))]
    [Migration("20240117194356_novamigracija")]
    partial class novamigracija
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("RIGProjeck.Class.Nepremičnina", b =>
                {
                    b.Property<int>("NepremičninaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Komentarji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ocena")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("cena")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("dan_izgradnje")
                        .HasColumnType("TEXT");

                    b.Property<string>("lokacija")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("stevilo_balkonov")
                        .HasColumnType("INTEGER");

                    b.Property<int>("stevilo_kopalnic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("stevilo_prostorov")
                        .HasColumnType("INTEGER");

                    b.Property<int>("stevilo_spalnic")
                        .HasColumnType("INTEGER");

                    b.Property<int>("uporabnikov_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("velikost")
                        .HasColumnType("INTEGER");

                    b.HasKey("NepremičninaID");

                    b.HasIndex("UserId");

                    b.ToTable("Nepremicninas");
                });

            modelBuilder.Entity("RIGProjeck.Class.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("verified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RIGProjeck.Class.Nepremičnina", b =>
                {
                    b.HasOne("RIGProjeck.Class.User", null)
                        .WithMany("uporabnikoveObjave")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("RIGProjeck.Class.User", b =>
                {
                    b.Navigation("uporabnikoveObjave");
                });
#pragma warning restore 612, 618
        }
    }
}
