name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub

        uses: docker/login-action@v1

        with:

          username: ${{ secrets.DOCKER_USERNAME }}

          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image

        uses: docker/build-push-action@v2

        with:

          context: .

          file: ./Dockerfile

          push: true

          tags: uporabnisko_ime/ime_slike:latest
